import oclif from 'eslint-config-oclif'

export default [
  {
    ignores: ['lib/'],
  },
  ...oclif,
  {
    rules: {
      // --- Style / formatting rules (this codebase has its own conventions) ---
      '@stylistic/block-spacing': 'off',
      '@stylistic/brace-style': 'off',
      '@stylistic/comma-dangle': 'off',
      '@stylistic/comma-spacing': 'off',
      '@stylistic/eol-last': 'off',
      '@stylistic/function-paren-newline': 'off',
      '@stylistic/indent': 'off',
      '@stylistic/indent-binary-ops': 'off',
      '@stylistic/key-spacing': 'off',
      '@stylistic/keyword-spacing': 'off',
      '@stylistic/lines-between-class-members': 'off',
      '@stylistic/max-len': 'off',
      '@stylistic/multiline-ternary': 'off',
      '@stylistic/no-trailing-spaces': 'off',
      '@stylistic/object-curly-newline': 'off',
      '@stylistic/object-curly-spacing': 'off',
      '@stylistic/operator-linebreak': 'off',
      '@stylistic/padded-blocks': 'off',
      '@stylistic/padding-line-between-statements': 'off',
      '@stylistic/quote-props': 'off',
      '@stylistic/quotes': 'off',
      '@stylistic/space-infix-ops': 'off',
      '@stylistic/arrow-parens': 'off',

      // --- Perfectionist (sorting) rules ---
      'perfectionist/sort-classes': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-intersection-types': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-object-types': 'off',
      'perfectionist/sort-objects': 'off',
      'perfectionist/sort-sets': 'off',
      'perfectionist/sort-switch-case': 'off',
      'perfectionist/sort-union-types': 'off',

      // --- Unicorn rules ---
      'unicorn/catch-error-name': 'off',
      'unicorn/empty-brace-spaces': 'off',
      'unicorn/import-style': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-instanceof-array': 'off',
      'unicorn/no-lonely-if': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/no-object-as-default-parameter': 'off',
      'unicorn/no-process-exit': 'off',
      'unicorn/no-useless-spread': 'off',
      'unicorn/numeric-separators-style': 'off',
      'unicorn/prefer-array-flat-map': 'off',
      'unicorn/prefer-array-some': 'off',
      'unicorn/prefer-global-this': 'off',
      'unicorn/prefer-includes': 'off',
      'unicorn/prefer-logical-operator-over-ternary': 'off',
      'unicorn/prefer-module': 'off',
      'unicorn/prefer-native-coercion-functions': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unicorn/prefer-optional-catch-binding': 'off',
      'unicorn/prefer-regexp-test': 'off',
      'unicorn/prefer-set-has': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/switch-case-braces': 'off',

      // --- TypeScript rules (too strict for legacy codebase) ---
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_|^error$|^e$|^err$',
        varsIgnorePattern: '^_',
      }],

      // --- Core ESLint rules (intentional patterns in codebase) ---
      'arrow-body-style': 'off',
      'camelcase': 'off',
      'complexity': 'off',
      'eqeqeq': 'off',
      'max-depth': 'off',
      'no-await-in-loop': 'off',
      'no-fallthrough': 'off',
      'no-implicit-coercion': 'off',
      'no-new': 'off',
      'no-return-assign': 'off',
      'no-throw-literal': 'off',
      'no-unneeded-ternary': 'off',
      'no-useless-escape': 'off',
      'no-useless-rename': 'off',
      'object-shorthand': 'off',
      'prefer-const': 'off',
      'prefer-destructuring': 'off',
      'prefer-object-spread': 'off',
      'radix': 'off',

      // --- Node plugin ---
      'n/no-extraneous-import': 'off',
      'n/no-process-exit': 'off',
      'node/no-unsupported-features/node-builtins': 'off',

      // --- Import plugin ---
      'import/no-named-as-default': 'off',
    },
  },
]
